<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-T16E1IM" failures="1" tests="6" name="Test" time="0.238" errors="0" timestamp="2022-02-01T17:01:11 IST">
  <testcase classname="com.testingfeatures.Retry_Analayzer" name="Login" time="0.019">
    <skipped/>
  </testcase> <!-- Login -->
  <testcase classname="com.testingfeatures.Retry_Analayzer" name="Login" time="0.008">
    <skipped/>
  </testcase> <!-- Login -->
  <testcase classname="com.testingfeatures.Retry_Analayzer" name="Login" time="0.008">
    <skipped/>
  </testcase> <!-- Login -->
  <testcase classname="com.testingfeatures.Retry_Analayzer" name="Login" time="0.008">
    <skipped/>
  </testcase> <!-- Login -->
  <testcase classname="com.testingfeatures.Retry_Analayzer" name="Login" time="0.015">
    <failure type="java.lang.AssertionError" message="expected [ayyapa] but found [Ayyapa]">
      <![CDATA[java.lang.AssertionError: expected [ayyapa] but found [Ayyapa]
at com.testingfeatures.Retry_Analayzer.Login(Retry_Analayzer.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Login -->
  <testcase classname="com.testingfeatures.Retry_Analayzer" name="Password" time="0.005"/>
</testsuite> <!-- Test -->
